### ISSUE TITLE
not compatible with kaminari

### ISSUE THREAD

**Issue by patcito** [lastomato/mongoid_followable#3]
Doing @user.followees_by_type('user').page(params[:page]) returns "undefined method page". Would it be possible to have it work with paginators?

**Comment by lastomato** [comment]
Did you try this?

``` ruby
Kaminari.paginate_array(my_array_object).page(params[:page]).per(10)
```

Actually, any array with these methods will do the job. You can open Array class and add these methods yourself. But this is just an alternative way, you'd better use the above solution.

Just a note, I stopped updating this gem since last Nov, check mongo_followable instead if you like:)

**Comment by patcito** [comment]
Cool, thanks a lot.
